"""
Materials Catalog for MillForge Manufacturing Intelligence Platform

Comprehensive catalog of engineered materials with process compatibility,
machinability ratings, thermal properties, and cost data.

Real engineering values sourced from:
- ASM Handbook Vol 2 (Properties and Selection)
- MatWeb materials database
- CRC Materials Science and Engineering Handbook
- Manufacturer datasheets (Carpenter, Haynes, Alcoa, etc.)
"""

from typing import Optional

MATERIALS_CATALOG = {
    # CARBON STEELS
    "carbon_steel_1018": {
        "name": "Carbon Steel 1018",
        "family": "carbon_steel",
        "common_names": ["ASTM A36", "mild steel 1018", "low-carbon steel"],
        "machinability_rating": 0.72,
        "hardness_typical": "89–126 HB",
        "density_g_cm3": 7.87,
        "tensile_strength_mpa": 440,
        "thermal_conductivity_w_mk": 51.9,
        "weldability": "excellent",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "bending_press_brake", "cutting_laser", "cutting_waterjet", "stamping"],
        "notes": "Free-machining, excellent weldability, low cost. Ideal for prototypes and general-purpose machining.",
        "cost_relative": "low",
    },
    "carbon_steel_1045": {
        "name": "Carbon Steel 1045",
        "family": "carbon_steel",
        "common_names": ["medium-carbon steel 1045", "1045 steel"],
        "machinability_rating": 0.65,
        "hardness_typical": "170–210 HB",
        "density_g_cm3": 7.85,
        "tensile_strength_mpa": 565,
        "thermal_conductivity_w_mk": 50.2,
        "weldability": "good",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "bending_press_brake", "cutting_laser", "cutting_waterjet", "stamping"],
        "notes": "Medium-carbon, higher strength than 1018, hardenable. Good for gears, shafts, and components requiring moderate strength.",
        "cost_relative": "low",
    },
    "carbon_steel_1060": {
        "name": "Carbon Steel 1060",
        "family": "carbon_steel",
        "common_names": ["high-carbon steel 1060"],
        "machinability_rating": 0.52,
        "hardness_typical": "212–260 HB",
        "density_g_cm3": 7.84,
        "tensile_strength_mpa": 700,
        "thermal_conductivity_w_mk": 49.8,
        "weldability": "fair",
        "suitable_processes": ["cnc_milling", "cnc_turning", "bending_press_brake", "cutting_laser", "cutting_waterjet"],
        "notes": "High-carbon content, excellent hardness after heat treat. Difficult to weld. Used for springs, tools, cutlery.",
        "cost_relative": "low",
    },
    "carbon_steel_1080": {
        "name": "Carbon Steel 1080",
        "family": "carbon_steel",
        "common_names": ["1080 steel", "spring steel"],
        "machinability_rating": 0.45,
        "hardness_typical": "236–285 HB",
        "density_g_cm3": 7.84,
        "tensile_strength_mpa": 770,
        "thermal_conductivity_w_mk": 49.8,
        "weldability": "poor",
        "suitable_processes": ["cnc_milling", "cnc_turning", "bending_press_brake", "cutting_laser"],
        "notes": "Very high carbon, excellent spring properties, high hardness. Difficult to machine and weld. For springs and cutting tools.",
        "cost_relative": "low",
    },

    # ALLOY STEELS
    "alloy_steel_4130": {
        "name": "Alloy Steel 4130",
        "family": "carbon_steel",
        "common_names": ["Chromoly 4130", "SAE 4130", "aircraft steel"],
        "machinability_rating": 0.67,
        "hardness_typical": "241–285 HB",
        "density_g_cm3": 7.85,
        "tensile_strength_mpa": 560,
        "thermal_conductivity_w_mk": 42.6,
        "weldability": "good",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "bending_press_brake", "cutting_laser", "cutting_waterjet"],
        "notes": "Chrome-molybdenum alloy, excellent strength-to-weight ratio. Used in aerospace, bicycles, tubing. Good weldability.",
        "cost_relative": "medium",
    },
    "alloy_steel_4140": {
        "name": "Alloy Steel 4140",
        "family": "carbon_steel",
        "common_names": ["Chromoly 4140", "SAE 4140"],
        "machinability_rating": 0.62,
        "hardness_typical": "280–330 HB",
        "density_g_cm3": 7.85,
        "tensile_strength_mpa": 655,
        "thermal_conductivity_w_mk": 42.6,
        "weldability": "good",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "bending_press_brake", "cutting_laser", "cutting_waterjet"],
        "notes": "High-strength chromoly, widely used in shafts, gears, and high-stress components. Good machinability.",
        "cost_relative": "medium",
    },
    "alloy_steel_4340": {
        "name": "Alloy Steel 4340",
        "family": "carbon_steel",
        "common_names": ["SAE 4340", "nickel-chromoly"],
        "machinability_rating": 0.55,
        "hardness_typical": "290–350 HB",
        "density_g_cm3": 7.84,
        "tensile_strength_mpa": 745,
        "thermal_conductivity_w_mk": 42.6,
        "weldability": "fair",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "bending_press_brake", "cutting_laser"],
        "notes": "Nickel-chromoly-molybdenum, very high strength, used in landing gear, crankshafts. Requires careful heat treat.",
        "cost_relative": "medium",
    },
    "alloy_steel_8620": {
        "name": "Alloy Steel 8620",
        "family": "carbon_steel",
        "common_names": ["SAE 8620", "case-hardening steel"],
        "machinability_rating": 0.68,
        "hardness_typical": "217–262 HB (core)",
        "density_g_cm3": 7.84,
        "tensile_strength_mpa": 520,
        "thermal_conductivity_w_mk": 47.9,
        "weldability": "good",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "bending_press_brake", "cutting_laser"],
        "notes": "Case-hardening steel with nickel-chromoly-molybdenum. Hard surface, tough core. For gears, bearings, fasteners.",
        "cost_relative": "medium",
    },
    "alloy_steel_52100": {
        "name": "Alloy Steel 52100",
        "family": "carbon_steel",
        "common_names": ["bearing steel 52100", "SAE 52100"],
        "machinability_rating": 0.48,
        "hardness_typical": "285–320 HB",
        "density_g_cm3": 7.81,
        "tensile_strength_mpa": 1275,
        "thermal_conductivity_w_mk": 47.9,
        "weldability": "poor",
        "suitable_processes": ["cnc_milling", "cnc_turning", "edm_sinker", "cutting_laser"],
        "notes": "High-carbon chromium bearing steel, very hard and wear-resistant. Difficult to machine. For bearings, races, tool steel.",
        "cost_relative": "medium",
    },

    # STAINLESS STEELS
    "stainless_steel_303": {
        "name": "Stainless Steel 303",
        "family": "stainless_steel",
        "common_names": ["austenitic 303", "free-machining stainless"],
        "machinability_rating": 0.80,
        "hardness_typical": "217–310 HB",
        "density_g_cm3": 7.48,
        "tensile_strength_mpa": 515,
        "thermal_conductivity_w_mk": 16.3,
        "weldability": "fair",
        "suitable_processes": ["cnc_milling", "cnc_turning", "bending_press_brake", "cutting_laser", "cutting_waterjet", "stamping"],
        "notes": "Best machinability of austenitic stainless due to selenium addition. Lower corrosion resistance. Ideal for screw machine products.",
        "cost_relative": "medium",
    },
    "stainless_steel_304": {
        "name": "Stainless Steel 304",
        "family": "stainless_steel",
        "common_names": ["austenitic 304", "18/8 stainless"],
        "machinability_rating": 0.50,
        "hardness_typical": "217–310 HB",
        "density_g_cm3": 8.0,
        "tensile_strength_mpa": 515,
        "thermal_conductivity_w_mk": 16.3,
        "weldability": "excellent",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "welding_laser", "bending_press_brake", "cutting_laser", "cutting_waterjet", "stamping"],
        "notes": "Most common austenitic stainless. Excellent corrosion resistance, weldability. Used in food, chemical, architectural applications.",
        "cost_relative": "medium",
    },
    "stainless_steel_316": {
        "name": "Stainless Steel 316",
        "family": "stainless_steel",
        "common_names": ["austenitic 316", "molybdenum stainless"],
        "machinability_rating": 0.48,
        "hardness_typical": "217–310 HB",
        "density_g_cm3": 8.0,
        "tensile_strength_mpa": 515,
        "thermal_conductivity_w_mk": 16.3,
        "weldability": "excellent",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "welding_laser", "bending_press_brake", "cutting_laser", "cutting_waterjet"],
        "notes": "Molybdenum addition improves pitting resistance, especially in chloride environments. For marine and offshore applications.",
        "cost_relative": "medium",
    },
    "stainless_steel_316l": {
        "name": "Stainless Steel 316L",
        "family": "stainless_steel",
        "common_names": ["austenitic 316L", "low-carbon 316"],
        "machinability_rating": 0.48,
        "hardness_typical": "217–310 HB",
        "density_g_cm3": 8.0,
        "tensile_strength_mpa": 485,
        "thermal_conductivity_w_mk": 16.3,
        "weldability": "excellent",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "welding_laser", "bending_press_brake", "cutting_laser", "cutting_waterjet"],
        "notes": "Low-carbon version of 316, reduces sensitization to carbide precipitation. Better for welded structures.",
        "cost_relative": "medium",
    },
    "stainless_steel_410": {
        "name": "Stainless Steel 410",
        "family": "stainless_steel",
        "common_names": ["martensitic 410", "hardenable stainless"],
        "machinability_rating": 0.65,
        "hardness_typical": "22–32 HRC (hardened)",
        "density_g_cm3": 7.75,
        "tensile_strength_mpa": 415,
        "thermal_conductivity_w_mk": 24.8,
        "weldability": "fair",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "bending_press_brake", "cutting_laser", "stamping"],
        "notes": "Martensitic, hardenable, moderate corrosion resistance. Used for cutlery, pump shafts, turbine blades. Can be hardened to 40 HRC.",
        "cost_relative": "medium",
    },
    "stainless_steel_420": {
        "name": "Stainless Steel 420",
        "family": "stainless_steel",
        "common_names": ["martensitic 420", "cutlery steel"],
        "machinability_rating": 0.55,
        "hardness_typical": "38–43 HRC (hardened)",
        "density_g_cm3": 7.75,
        "tensile_strength_mpa": 480,
        "thermal_conductivity_w_mk": 24.8,
        "weldability": "fair",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "bending_press_brake", "cutting_laser"],
        "notes": "Higher carbon than 410, hardness up to 43 HRC. Used for cutlery, gauges, surgical instruments. Fair corrosion resistance.",
        "cost_relative": "medium",
    },
    "stainless_steel_440c": {
        "name": "Stainless Steel 440C",
        "family": "stainless_steel",
        "common_names": ["martensitic 440C", "high-carbon stainless"],
        "machinability_rating": 0.35,
        "hardness_typical": "54–60 HRC (hardened)",
        "density_g_cm3": 7.75,
        "tensile_strength_mpa": 700,
        "thermal_conductivity_w_mk": 24.8,
        "weldability": "poor",
        "suitable_processes": ["cnc_milling", "cnc_turning", "edm_sinker", "edm_wire", "cutting_laser"],
        "notes": "Very hard martensitic stainless, highest hardness of all stainless grades. Difficult to machine. For precision bearings and gauges.",
        "cost_relative": "medium",
    },
    "stainless_steel_17_4_ph": {
        "name": "Stainless Steel 17-4 PH",
        "family": "stainless_steel",
        "common_names": ["17-4 precipitation-hardening", "UNS S17400"],
        "machinability_rating": 0.45,
        "hardness_typical": "38–48 HRC (H1025 condition)",
        "density_g_cm3": 7.81,
        "tensile_strength_mpa": 1310,
        "thermal_conductivity_w_mk": 11.4,
        "weldability": "good",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "bending_press_brake", "cutting_laser", "edm_sinker"],
        "notes": "Precipitation-hardening, high strength at elevated temperature. Used in aerospace, oil tools, pump components. Age-hardenable.",
        "cost_relative": "high",
    },
    "stainless_steel_15_5_ph": {
        "name": "Stainless Steel 15-5 PH",
        "family": "stainless_steel",
        "common_names": ["15-5 precipitation-hardening", "UNS S15500"],
        "machinability_rating": 0.50,
        "hardness_typical": "38–48 HRC (H1025 condition)",
        "density_g_cm3": 7.80,
        "tensile_strength_mpa": 1310,
        "thermal_conductivity_w_mk": 11.0,
        "weldability": "good",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "bending_press_brake", "cutting_laser", "edm_sinker"],
        "notes": "Precipitation-hardening, similar to 17-4 PH with slightly lower nickel. Better machinability. For high-strength fasteners and springs.",
        "cost_relative": "high",
    },
    "stainless_steel_2205_duplex": {
        "name": "Stainless Steel 2205 Duplex",
        "family": "stainless_steel",
        "common_names": ["duplex 2205", "super duplex", "austenitic-ferritic"],
        "machinability_rating": 0.48,
        "hardness_typical": "305–363 HB",
        "density_g_cm3": 7.80,
        "tensile_strength_mpa": 620,
        "thermal_conductivity_w_mk": 16.3,
        "weldability": "good",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "welding_laser", "bending_press_brake", "cutting_laser", "cutting_waterjet"],
        "notes": "Duplex structure (50% austenite, 50% ferrite). High strength and pitting resistance. For subsea, chemical processing.",
        "cost_relative": "high",
    },

    # TOOL STEELS
    "tool_steel_a2": {
        "name": "Tool Steel A2",
        "family": "tool_steel",
        "common_names": ["air-hardening tool steel A2", "ASTM A681"],
        "machinability_rating": 0.45,
        "hardness_typical": "58–62 HRC (hardened)",
        "density_g_cm3": 7.30,
        "tensile_strength_mpa": 1620,
        "thermal_conductivity_w_mk": 25.6,
        "weldability": "poor",
        "suitable_processes": ["cnc_milling", "cnc_turning", "edm_sinker", "edm_wire", "cutting_laser"],
        "notes": "Air-hardening tool steel, minimal distortion. High hardness, good wear resistance. Used for punches, gauges, shears.",
        "cost_relative": "medium",
    },
    "tool_steel_d2": {
        "name": "Tool Steel D2",
        "family": "tool_steel",
        "common_names": ["cold-die tool steel D2", "ASTM A681"],
        "machinability_rating": 0.35,
        "hardness_typical": "61–65 HRC (hardened)",
        "density_g_cm3": 7.75,
        "tensile_strength_mpa": 1930,
        "thermal_conductivity_w_mk": 21.0,
        "weldability": "poor",
        "suitable_processes": ["cnc_milling", "cnc_turning", "edm_sinker", "edm_wire", "cutting_laser"],
        "notes": "High carbon, chromium cold-work steel. Very hard, excellent wear resistance. For dies, punches, shears, gauges.",
        "cost_relative": "medium",
    },
    "tool_steel_h13": {
        "name": "Tool Steel H13",
        "family": "tool_steel",
        "common_names": ["hot-die tool steel H13", "ASTM A681"],
        "machinability_rating": 0.48,
        "hardness_typical": "38–55 HRC (hardened)",
        "density_g_cm3": 7.25,
        "tensile_strength_mpa": 1330,
        "thermal_conductivity_w_mk": 25.1,
        "weldability": "fair",
        "suitable_processes": ["cnc_milling", "cnc_turning", "edm_sinker", "edm_wire", "welding_arc", "cutting_laser"],
        "notes": "Chromium hot-work steel, excellent thermal fatigue resistance. Used for hot-forming dies, extrusion dies.",
        "cost_relative": "high",
    },
    "tool_steel_m2": {
        "name": "Tool Steel M2",
        "family": "tool_steel",
        "common_names": ["tungsten high-speed steel M2", "HSS M2"],
        "machinability_rating": 0.22,
        "hardness_typical": "62–65 HRC (hardened)",
        "density_g_cm3": 8.80,
        "tensile_strength_mpa": 1515,
        "thermal_conductivity_w_mk": 23.3,
        "weldability": "poor",
        "suitable_processes": ["cnc_milling", "cnc_turning", "edm_sinker", "edm_wire", "cutting_laser"],
        "notes": "Tungsten molybdenum high-speed steel. Very hard, heat-resistant to 600°C. For cutting tools, drills, taps.",
        "cost_relative": "medium",
    },
    "tool_steel_o1": {
        "name": "Tool Steel O1",
        "family": "tool_steel",
        "common_names": ["oil-hardening tool steel O1", "ASTM A681"],
        "machinability_rating": 0.50,
        "hardness_typical": "58–62 HRC (hardened)",
        "density_g_cm3": 7.68,
        "tensile_strength_mpa": 1515,
        "thermal_conductivity_w_mk": 46.9,
        "weldability": "fair",
        "suitable_processes": ["cnc_milling", "cnc_turning", "edm_sinker", "edm_wire", "welding_arc", "cutting_laser"],
        "notes": "Oil-hardening, moderate distortion. For gauges, precision tools, arbors. Good machinability in annealed state.",
        "cost_relative": "medium",
    },
    "tool_steel_p20": {
        "name": "Tool Steel P20",
        "family": "tool_steel",
        "common_names": ["plastic-die tool steel P20", "ASTM A681"],
        "machinability_rating": 0.75,
        "hardness_typical": "28–35 HRC (prehardened)",
        "density_g_cm3": 7.40,
        "tensile_strength_mpa": 1380,
        "thermal_conductivity_w_mk": 27.0,
        "weldability": "good",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "bending_press_brake", "cutting_laser", "edm_sinker"],
        "notes": "Prehardened plastic mold steel, excellent machinability. Can be hardened further. Low cost, widely used.",
        "cost_relative": "medium",
    },
    "tool_steel_s7": {
        "name": "Tool Steel S7",
        "family": "tool_steel",
        "common_names": ["shock-resisting tool steel S7", "ASTM A681"],
        "machinability_rating": 0.52,
        "hardness_typical": "48–54 HRC (hardened)",
        "density_g_cm3": 7.75,
        "tensile_strength_mpa": 1655,
        "thermal_conductivity_w_mk": 42.7,
        "weldability": "fair",
        "suitable_processes": ["cnc_milling", "cnc_turning", "edm_sinker", "edm_wire", "welding_arc", "cutting_laser"],
        "notes": "Shock-resisting steel, excellent toughness. For pneumatic tools, chisels, shear blades.",
        "cost_relative": "medium",
    },

    # ALUMINUM ALLOYS
    "aluminum_alloy_2011": {
        "name": "Aluminum Alloy 2011",
        "family": "aluminum_alloy",
        "common_names": ["2011-T3", "free-machining aluminum"],
        "machinability_rating": 0.85,
        "hardness_typical": "95–105 HB",
        "density_g_cm3": 2.71,
        "tensile_strength_mpa": 380,
        "thermal_conductivity_w_mk": 142,
        "weldability": "fair",
        "suitable_processes": ["cnc_milling", "cnc_turning", "stamping", "cutting_laser", "cutting_waterjet"],
        "notes": "Best machinability of aluminum alloys due to lead and bismuth additions. Not weldable. For screw machine products.",
        "cost_relative": "medium",
    },
    "aluminum_alloy_2024": {
        "name": "Aluminum Alloy 2024",
        "family": "aluminum_alloy",
        "common_names": ["2024-T3", "2024-T4", "Duralumin"],
        "machinability_rating": 0.60,
        "hardness_typical": "120–150 HB",
        "density_g_cm3": 2.78,
        "tensile_strength_mpa": 470,
        "thermal_conductivity_w_mk": 121,
        "weldability": "poor",
        "suitable_processes": ["cnc_milling", "cnc_turning", "bending_press_brake", "cutting_laser", "cutting_waterjet", "stamping"],
        "notes": "High-strength aluminum, excellent fatigue resistance. Not suitable for welding. Used in aerospace structures.",
        "cost_relative": "medium",
    },
    "aluminum_alloy_5052": {
        "name": "Aluminum Alloy 5052",
        "family": "aluminum_alloy",
        "common_names": ["5052-H32", "5052-O"],
        "machinability_rating": 0.50,
        "hardness_typical": "60–77 HB",
        "density_g_cm3": 2.68,
        "tensile_strength_mpa": 260,
        "thermal_conductivity_w_mk": 138,
        "weldability": "excellent",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "welding_laser", "bending_press_brake", "cutting_laser", "cutting_waterjet", "stamping"],
        "notes": "Non-heat-treatable, excellent seawater corrosion resistance. Easy to form and weld. For marine applications.",
        "cost_relative": "low",
    },
    "aluminum_alloy_5083": {
        "name": "Aluminum Alloy 5083",
        "family": "aluminum_alloy",
        "common_names": ["5083-H321", "5083-O"],
        "machinability_rating": 0.45,
        "hardness_typical": "75–96 HB",
        "density_g_cm3": 2.66,
        "tensile_strength_mpa": 315,
        "thermal_conductivity_w_mk": 121,
        "weldability": "excellent",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "welding_laser", "bending_press_brake", "cutting_laser", "cutting_waterjet", "stamping"],
        "notes": "Highest magnesium content non-heat-treatable aluminum. Marine-grade, excellent corrosion resistance.",
        "cost_relative": "low",
    },
    "aluminum_alloy_6061": {
        "name": "Aluminum Alloy 6061",
        "family": "aluminum_alloy",
        "common_names": ["6061-T6", "6061-T4"],
        "machinability_rating": 0.55,
        "hardness_typical": "95–110 HB",
        "density_g_cm3": 2.70,
        "tensile_strength_mpa": 310,
        "thermal_conductivity_w_mk": 167,
        "weldability": "good",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "welding_laser", "bending_press_brake", "cutting_laser", "cutting_waterjet", "stamping"],
        "notes": "Most versatile aluminum alloy. Good strength, weldability, and corrosion resistance. General-purpose engineering.",
        "cost_relative": "low",
    },
    "aluminum_alloy_6063": {
        "name": "Aluminum Alloy 6063",
        "family": "aluminum_alloy",
        "common_names": ["6063-T5", "6063-T6"],
        "machinability_rating": 0.60,
        "hardness_typical": "73–100 HB",
        "density_g_cm3": 2.69,
        "tensile_strength_mpa": 240,
        "thermal_conductivity_w_mk": 201,
        "weldability": "excellent",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "welding_laser", "bending_press_brake", "cutting_laser", "cutting_waterjet", "stamping"],
        "notes": "Excellent extrusion alloy, good machinability and weldability. Lower strength than 6061. For architectural profiles.",
        "cost_relative": "low",
    },
    "aluminum_alloy_7050": {
        "name": "Aluminum Alloy 7050",
        "family": "aluminum_alloy",
        "common_names": ["7050-T7451", "7050-T76"],
        "machinability_rating": 0.48,
        "hardness_typical": "150–180 HB",
        "density_g_cm3": 2.83,
        "tensile_strength_mpa": 540,
        "thermal_conductivity_w_mk": 130,
        "weldability": "poor",
        "suitable_processes": ["cnc_milling", "cnc_turning", "bending_press_brake", "cutting_laser", "edm_sinker"],
        "notes": "Very high strength, better stress-corrosion cracking resistance than 7075. For aerospace forgings and extrusions.",
        "cost_relative": "high",
    },
    "aluminum_alloy_7075": {
        "name": "Aluminum Alloy 7075",
        "family": "aluminum_alloy",
        "common_names": ["7075-T6", "7075-T73"],
        "machinability_rating": 0.38,
        "hardness_typical": "150–190 HB",
        "density_g_cm3": 2.81,
        "tensile_strength_mpa": 570,
        "thermal_conductivity_w_mk": 130,
        "weldability": "poor",
        "suitable_processes": ["cnc_milling", "cnc_turning", "bending_press_brake", "cutting_laser", "edm_sinker", "edm_wire"],
        "notes": "Highest strength aluminum alloy. Difficult to machine. Not weldable. For aircraft wings, fuselages.",
        "cost_relative": "high",
    },
    "aluminum_alloy_7068": {
        "name": "Aluminum Alloy 7068",
        "family": "aluminum_alloy",
        "common_names": ["7068-T6511", "7068-T6"],
        "machinability_rating": 0.35,
        "hardness_typical": "155–200 HB",
        "density_g_cm3": 2.81,
        "tensile_strength_mpa": 620,
        "thermal_conductivity_w_mk": 130,
        "weldability": "poor",
        "suitable_processes": ["cnc_milling", "cnc_turning", "cutting_laser", "edm_sinker", "edm_wire"],
        "notes": "Extremely high strength, enhanced toughness vs 7075. For military-spec applications, landing gear.",
        "cost_relative": "very_high",
    },

    # TITANIUM ALLOYS
    "titanium_grade_1": {
        "name": "Titanium Grade 1",
        "family": "titanium_alloy",
        "common_names": ["CP titanium grade 1", "unalloyed titanium"],
        "machinability_rating": 0.45,
        "hardness_typical": "167–237 HB",
        "density_g_cm3": 4.51,
        "tensile_strength_mpa": 345,
        "thermal_conductivity_w_mk": 17.4,
        "weldability": "excellent",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "welding_laser", "bending_press_brake", "cutting_laser", "cutting_waterjet"],
        "notes": "Commercially pure titanium, lowest strength but excellent corrosion resistance. For chemical processing, heat exchangers.",
        "cost_relative": "high",
    },
    "titanium_grade_2": {
        "name": "Titanium Grade 2",
        "family": "titanium_alloy",
        "common_names": ["CP titanium grade 2", "commercially pure titanium"],
        "machinability_rating": 0.42,
        "hardness_typical": "167–250 HB",
        "density_g_cm3": 4.51,
        "tensile_strength_mpa": 415,
        "thermal_conductivity_w_mk": 17.4,
        "weldability": "excellent",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "welding_laser", "bending_press_brake", "cutting_laser", "cutting_waterjet"],
        "notes": "Most commercially pure titanium, excellent corrosion resistance and weldability. General-purpose applications.",
        "cost_relative": "high",
    },
    "titanium_grade_5": {
        "name": "Titanium Grade 5 (Ti-6Al-4V)",
        "family": "titanium_alloy",
        "common_names": ["Ti-6Al-4V", "6-4 titanium", "Ti-6-4"],
        "machinability_rating": 0.30,
        "hardness_typical": "334–363 HB",
        "density_g_cm3": 4.43,
        "tensile_strength_mpa": 1160,
        "thermal_conductivity_w_mk": 7.4,
        "weldability": "good",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "welding_laser", "welding_ebw", "bending_press_brake", "cutting_laser", "cutting_waterjet", "edm_sinker"],
        "notes": "Most widely used titanium alloy, excellent strength-to-weight ratio. Used in aerospace, medical implants, racing.",
        "cost_relative": "very_high",
    },
    "titanium_grade_9": {
        "name": "Titanium Grade 9 (Ti-3Al-2.5V)",
        "family": "titanium_alloy",
        "common_names": ["Ti-3Al-2.5V", "3-2.5 titanium"],
        "machinability_rating": 0.35,
        "hardness_typical": "265–310 HB",
        "density_g_cm3": 4.51,
        "tensile_strength_mpa": 620,
        "thermal_conductivity_w_mk": 16.4,
        "weldability": "excellent",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "welding_laser", "bending_press_brake", "cutting_laser", "cutting_waterjet"],
        "notes": "Lower alloy content than Grade 5, better weldability. For fabricated structures, tubing, pressure vessels.",
        "cost_relative": "high",
    },
    "titanium_ti_6al_4v_eli": {
        "name": "Titanium Ti-6Al-4V ELI",
        "family": "titanium_alloy",
        "common_names": ["Ti-6Al-4V ELI", "6-4 ELI", "medical grade"],
        "machinability_rating": 0.28,
        "hardness_typical": "334–363 HB",
        "density_g_cm3": 4.43,
        "tensile_strength_mpa": 1160,
        "thermal_conductivity_w_mk": 7.4,
        "weldability": "good",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "welding_laser", "welding_ebw", "bending_press_brake", "cutting_laser", "edm_sinker"],
        "notes": "Extra-low interstitials for improved fatigue and fracture toughness. For orthopedic implants and cardiovascular devices.",
        "cost_relative": "very_high",
    },
    "titanium_ti_6al_2sn_4zr_2mo": {
        "name": "Titanium Ti-6Al-2Sn-4Zr-2Mo",
        "family": "titanium_alloy",
        "common_names": ["Ti-6242", "near-alpha alloy"],
        "machinability_rating": 0.25,
        "hardness_typical": "340–380 HB",
        "density_g_cm3": 4.54,
        "tensile_strength_mpa": 1050,
        "thermal_conductivity_w_mk": 6.1,
        "weldability": "fair",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "welding_ebw", "bending_press_brake", "cutting_laser", "edm_sinker"],
        "notes": "Near-alpha alloy, excellent creep resistance to 600°C. For turbine engines, compressor blades.",
        "cost_relative": "very_high",
    },

    # NICKEL SUPERALLOYS
    "nickel_inconel_625": {
        "name": "Nickel Inconel 625",
        "family": "nickel_alloy",
        "common_names": ["Inconel 625", "UNS N06625", "alloy 625"],
        "machinability_rating": 0.18,
        "hardness_typical": "225–290 HB",
        "density_g_cm3": 8.44,
        "tensile_strength_mpa": 1035,
        "thermal_conductivity_w_mk": 9.8,
        "weldability": "good",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "welding_laser", "welding_ebw", "cutting_laser", "edm_sinker", "edm_wire"],
        "notes": "Excellent corrosion resistance and strength to 980°C. Difficult to machine. Used in aerospace, chemical processing, oil/gas.",
        "cost_relative": "very_high",
    },
    "nickel_inconel_718": {
        "name": "Nickel Inconel 718",
        "family": "nickel_alloy",
        "common_names": ["Inconel 718", "UNS N07718", "alloy 718"],
        "machinability_rating": 0.15,
        "hardness_typical": "380–430 HB",
        "density_g_cm3": 8.19,
        "tensile_strength_mpa": 1275,
        "thermal_conductivity_w_mk": 11.4,
        "weldability": "good",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "welding_laser", "welding_ebw", "cutting_laser", "edm_sinker"],
        "notes": "Precipitation-hardening, strength to 650°C. Used for jet engine turbine disks, fasteners. Difficult to machine.",
        "cost_relative": "very_high",
    },
    "nickel_hastelloy_c276": {
        "name": "Nickel Hastelloy C-276",
        "family": "nickel_alloy",
        "common_names": ["Hastelloy C-276", "UNS N10276"],
        "machinability_rating": 0.20,
        "hardness_typical": "217–293 HB",
        "density_g_cm3": 8.89,
        "tensile_strength_mpa": 655,
        "thermal_conductivity_w_mk": 9.2,
        "weldability": "good",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "welding_laser", "welding_ebw", "cutting_laser", "edm_sinker"],
        "notes": "Excellent resistance to all forms of corrosion, including pitting. For chemical processing, pulp/paper mills.",
        "cost_relative": "very_high",
    },
    "nickel_waspaloy": {
        "name": "Nickel Waspaloy",
        "family": "nickel_alloy",
        "common_names": ["Waspaloy", "UNS N07001"],
        "machinability_rating": 0.12,
        "hardness_typical": "450–480 HB",
        "density_g_cm3": 8.80,
        "tensile_strength_mpa": 1380,
        "thermal_conductivity_w_mk": 11.8,
        "weldability": "fair",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "welding_ebw", "cutting_laser", "edm_sinker"],
        "notes": "High-temperature superalloy, excellent strength to 900°C. For turbine engines, combustion hardware.",
        "cost_relative": "very_high",
    },
    "nickel_rene_41": {
        "name": "Nickel Rene 41",
        "family": "nickel_alloy",
        "common_names": ["Rene 41", "UNS N07041"],
        "machinability_rating": 0.10,
        "hardness_typical": "440–490 HB",
        "density_g_cm3": 8.80,
        "tensile_strength_mpa": 1380,
        "thermal_conductivity_w_mk": 12.6,
        "weldability": "fair",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "welding_ebw", "cutting_laser", "edm_sinker"],
        "notes": "Precipitation-hardening superalloy, high strength to 870°C. For turbine blades, combustor parts.",
        "cost_relative": "very_high",
    },
    "nickel_monel_400": {
        "name": "Nickel Monel 400",
        "family": "nickel_alloy",
        "common_names": ["Monel 400", "UNS N04400"],
        "machinability_rating": 0.30,
        "hardness_typical": "120–180 HB",
        "density_g_cm3": 8.80,
        "tensile_strength_mpa": 480,
        "thermal_conductivity_w_mk": 25.0,
        "weldability": "good",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "bending_press_brake", "cutting_laser", "cutting_waterjet"],
        "notes": "Copper-nickel alloy, excellent corrosion resistance, good strength. For seawater applications, heat exchangers.",
        "cost_relative": "high",
    },

    # COPPER ALLOYS
    "copper_c110": {
        "name": "Copper C110",
        "family": "copper_alloy",
        "common_names": ["pure copper", "ASTM B152", "oxygen-free copper"],
        "machinability_rating": 0.65,
        "hardness_typical": "40–50 HB",
        "density_g_cm3": 8.94,
        "tensile_strength_mpa": 220,
        "thermal_conductivity_w_mk": 401,
        "weldability": "fair",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "bending_press_brake", "cutting_laser", "cutting_waterjet", "stamping"],
        "notes": "Pure copper, excellent electrical and thermal conductivity. Soft, low strength. For electrical components, busbars.",
        "cost_relative": "medium",
    },
    "copper_alloy_c260": {
        "name": "Copper Alloy C260 (Brass)",
        "family": "copper_alloy",
        "common_names": ["brass C260", "cartridge brass", "ASTM B36"],
        "machinability_rating": 0.70,
        "hardness_typical": "40–100 HB",
        "density_g_cm3": 8.53,
        "tensile_strength_mpa": 300,
        "thermal_conductivity_w_mk": 120,
        "weldability": "good",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "bending_press_brake", "cutting_laser", "cutting_waterjet", "stamping"],
        "notes": "Copper-zinc alloy, good formability and machinability. Used in ammunition, plumbing, decorative items.",
        "cost_relative": "medium",
    },
    "copper_alloy_c360": {
        "name": "Copper Alloy C360 (Free-Machining Brass)",
        "family": "copper_alloy",
        "common_names": ["free-cutting brass C360", "screw machine brass"],
        "machinability_rating": 0.85,
        "hardness_typical": "50–120 HB",
        "density_g_cm3": 8.47,
        "tensile_strength_mpa": 330,
        "thermal_conductivity_w_mk": 110,
        "weldability": "fair",
        "suitable_processes": ["cnc_milling", "cnc_turning", "stamping", "bending_press_brake", "cutting_laser"],
        "notes": "Lead addition for excellent machinability. Easiest copper alloy to machine. For screw machine products, fasteners.",
        "cost_relative": "medium",
    },
    "copper_alloy_c510": {
        "name": "Copper Alloy C510 (Phosphor Bronze)",
        "family": "copper_alloy",
        "common_names": ["phosphor bronze C510", "tin bronze"],
        "machinability_rating": 0.45,
        "hardness_typical": "80–140 HB",
        "density_g_cm3": 8.75,
        "tensile_strength_mpa": 450,
        "thermal_conductivity_w_mk": 51.0,
        "weldability": "fair",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "bending_press_brake", "casting", "cutting_laser"],
        "notes": "Copper-tin alloy, excellent fatigue and wear resistance. For springs, bearings, bushings, electrical contacts.",
        "cost_relative": "high",
    },
    "copper_alloy_c630": {
        "name": "Copper Alloy C630 (Aluminum Bronze)",
        "family": "copper_alloy",
        "common_names": ["aluminum bronze C630", "ASTM B148"],
        "machinability_rating": 0.40,
        "hardness_typical": "150–200 HB",
        "density_g_cm3": 7.72,
        "tensile_strength_mpa": 580,
        "thermal_conductivity_w_mk": 75.0,
        "weldability": "good",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "bending_press_brake", "casting", "cutting_laser"],
        "notes": "Copper-aluminum alloy, high strength, excellent corrosion resistance. For marine fittings, fasteners, gears.",
        "cost_relative": "high",
    },
    "copper_alloy_c954": {
        "name": "Copper Alloy C954 (Aluminum Bronze Casting)",
        "family": "copper_alloy",
        "common_names": ["aluminum bronze casting C954", "ASTM B626"],
        "machinability_rating": 0.35,
        "hardness_typical": "180–220 HB",
        "density_g_cm3": 7.70,
        "tensile_strength_mpa": 620,
        "thermal_conductivity_w_mk": 75.0,
        "weldability": "fair",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "casting", "cutting_laser"],
        "notes": "Cast aluminum bronze, high strength, corrosion resistance. For pump impellers, marine propellers.",
        "cost_relative": "high",
    },
    "copper_alloy_c172_beryllium": {
        "name": "Copper Alloy C172 (Beryllium Copper)",
        "family": "copper_alloy",
        "common_names": ["beryllium copper C172", "BeCu", "spring copper"],
        "machinability_rating": 0.35,
        "hardness_typical": "320–400 HB (hardened)",
        "density_g_cm3": 8.23,
        "tensile_strength_mpa": 1310,
        "thermal_conductivity_w_mk": 110,
        "weldability": "poor",
        "suitable_processes": ["cnc_milling", "cnc_turning", "bending_press_brake", "stamping", "cutting_laser"],
        "notes": "High strength, excellent spring properties, non-magnetic. Expensive, beryllium dust toxic. For precision springs, contacts.",
        "cost_relative": "very_high",
    },

    # COBALT ALLOYS
    "cobalt_stellite_6": {
        "name": "Cobalt Stellite 6",
        "family": "superalloy",
        "common_names": ["Stellite 6", "cobalt-chromium-tungsten alloy"],
        "machinability_rating": 0.15,
        "hardness_typical": "50–52 HRC",
        "density_g_cm3": 8.50,
        "tensile_strength_mpa": 720,
        "thermal_conductivity_w_mk": 12.8,
        "weldability": "poor",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "cutting_laser", "edm_sinker"],
        "notes": "Cobalt-chromium-tungsten casting alloy, excellent wear and corrosion resistance. For wear parts, valve seats, cutting tools.",
        "cost_relative": "very_high",
    },
    "cobalt_mp35n": {
        "name": "Cobalt MP35N",
        "family": "superalloy",
        "common_names": ["MP35N", "UNS R30035"],
        "machinability_rating": 0.12,
        "hardness_typical": "320–380 HB",
        "density_g_cm3": 9.30,
        "tensile_strength_mpa": 1590,
        "thermal_conductivity_w_mk": 10.5,
        "weldability": "fair",
        "suitable_processes": ["cnc_milling", "cnc_turning", "welding_arc", "welding_laser", "cutting_laser", "edm_sinker"],
        "notes": "High strength, excellent corrosion resistance. For medical implants, fasteners, connectors.",
        "cost_relative": "very_high",
    },

    # REFRACTORY METALS
    "refractory_tungsten": {
        "name": "Refractory Tungsten",
        "family": "refractory",
        "common_names": ["tungsten", "W"],
        "machinability_rating": 0.08,
        "hardness_typical": "200–250 HV",
        "density_g_cm3": 19.25,
        "tensile_strength_mpa": 450,
        "thermal_conductivity_w_mk": 173,
        "weldability": "poor",
        "suitable_processes": ["cnc_milling", "edm_sinker", "edm_wire", "cutting_laser"],
        "notes": "Highest melting point metal (3,422°C). Extremely dense and brittle. For electrodes, filaments, radiation shielding.",
        "cost_relative": "very_high",
    },
    "refractory_molybdenum": {
        "name": "Refractory Molybdenum",
        "family": "refractory",
        "common_names": ["molybdenum", "Mo"],
        "machinability_rating": 0.12,
        "hardness_typical": "150–200 HV",
        "density_g_cm3": 10.22,
        "tensile_strength_mpa": 345,
        "thermal_conductivity_w_mk": 142,
        "weldability": "poor",
        "suitable_processes": ["cnc_milling", "edm_sinker", "edm_wire", "cutting_laser"],
        "notes": "High melting point (2,623°C), corrosion-resistant, good strength. For furnace parts, electrodes.",
        "cost_relative": "very_high",
    },
    "refractory_tantalum": {
        "name": "Refractory Tantalum",
        "family": "refractory",
        "common_names": ["tantalum", "Ta"],
        "machinability_rating": 0.10,
        "hardness_typical": "100–150 HV",
        "density_g_cm3": 16.69,
        "tensile_strength_mpa": 310,
        "thermal_conductivity_w_mk": 57.5,
        "weldability": "poor",
        "suitable_processes": ["cnc_milling", "edm_sinker", "edm_wire"],
        "notes": "High melting point (3,017°C), excellent corrosion resistance, ductile. For chemical process equipment, capacitors.",
        "cost_relative": "very_high",
    },
    "refractory_niobium": {
        "name": "Refractory Niobium",
        "family": "refractory",
        "common_names": ["niobium", "Nb", "columbium"],
        "machinability_rating": 0.20,
        "hardness_typical": "100–130 HV",
        "density_g_cm3": 8.57,
        "tensile_strength_mpa": 350,
        "thermal_conductivity_w_mk": 51.4,
        "weldability": "poor",
        "suitable_processes": ["cnc_milling", "edm_sinker", "edm_wire", "cutting_laser"],
        "notes": "High melting point (2,477°C), good strength, ductile. Used in superalloys, aircraft engines, capacitors.",
        "cost_relative": "very_high",
    },

    # MAGNESIUM & ZINC
    "magnesium_alloy_az31b": {
        "name": "Magnesium Alloy AZ31B",
        "family": "aluminum_alloy",
        "common_names": ["AZ31B", "magnesium AZ31"],
        "machinability_rating": 0.75,
        "hardness_typical": "66–107 HB",
        "density_g_cm3": 1.77,
        "tensile_strength_mpa": 290,
        "thermal_conductivity_w_mk": 96.0,
        "weldability": "fair",
        "suitable_processes": ["cnc_milling", "cnc_turning", "bending_press_brake", "cutting_laser", "cutting_waterjet"],
        "notes": "Lightest structural metal, excellent machinability. Flammable at high temperatures. For aerospace, racing.",
        "cost_relative": "medium",
    },
    "zinc_alloy_zamak_3": {
        "name": "Zinc Alloy Zamak 3",
        "family": "aluminum_alloy",
        "common_names": ["Zamak 3", "zinc die-cast alloy"],
        "machinability_rating": 0.68,
        "hardness_typical": "82–108 HB",
        "density_g_cm3": 6.63,
        "tensile_strength_mpa": 280,
        "thermal_conductivity_w_mk": 121,
        "weldability": "poor",
        "suitable_processes": ["stamping", "cnc_milling", "cnc_turning", "cutting_laser"],
        "notes": "Zinc-aluminum-copper-magnesium alloy, excellent for die casting. Good machinability, brittle.",
        "cost_relative": "low",
    },

    # TITANIUM ALUMINIDE
    "titanium_aluminide": {
        "name": "Titanium Aluminide (TiAl)",
        "family": "titanium_alloy",
        "common_names": ["TiAl", "gamma-TiAl"],
        "machinability_rating": 0.08,
        "hardness_typical": "380–450 HB",
        "density_g_cm3": 3.75,
        "tensile_strength_mpa": 550,
        "thermal_conductivity_w_mk": 16.4,
        "weldability": "poor",
        "suitable_processes": ["cnc_milling", "cnc_turning", "edm_sinker", "edm_wire", "cutting_laser"],
        "notes": "Intermetallic compound, lightweight (40% lighter than Ti-6Al-4V), very brittle. For high-temperature turbine blades.",
        "cost_relative": "very_high",
    },

    # POLYMERS & PLASTICS
    "polymer_peek": {
        "name": "Polymer PEEK",
        "family": "polymer",
        "common_names": ["PEEK", "polyetheretherketone"],
        "machinability_rating": 0.65,
        "hardness_typical": "90–100 HB",
        "density_g_cm3": 1.32,
        "tensile_strength_mpa": 100,
        "thermal_conductivity_w_mk": 0.29,
        "weldability": "not_recommended",
        "suitable_processes": ["cnc_milling", "cnc_turning", "bending_press_brake", "cutting_laser", "cutting_waterjet"],
        "notes": "High-performance engineering plastic, excellent chemical and thermal resistance to 250°C. For aerospace, medical.",
        "cost_relative": "very_high",
    },
    "polymer_delrin": {
        "name": "Polymer Delrin (POM)",
        "family": "polymer",
        "common_names": ["Delrin", "POM", "acetal copolymer"],
        "machinability_rating": 0.80,
        "hardness_typical": "75–85 HB",
        "density_g_cm3": 1.41,
        "tensile_strength_mpa": 70,
        "thermal_conductivity_w_mk": 0.25,
        "weldability": "not_recommended",
        "suitable_processes": ["cnc_milling", "cnc_turning", "bending_press_brake", "cutting_laser", "cutting_waterjet"],
        "notes": "Excellent machinability, low friction. For gears, bearings, precision parts. Temperature limit ~85°C.",
        "cost_relative": "medium",
    },
    "polymer_nylon_6": {
        "name": "Polymer Nylon 6",
        "family": "polymer",
        "common_names": ["Nylon 6", "polyamide 6"],
        "machinability_rating": 0.70,
        "hardness_typical": "70–85 HB",
        "density_g_cm3": 1.14,
        "tensile_strength_mpa": 60,
        "thermal_conductivity_w_mk": 0.25,
        "weldability": "not_recommended",
        "suitable_processes": ["cnc_milling", "cnc_turning", "injection_molding", "cutting_laser", "cutting_waterjet", "stamping"],
        "notes": "Thermoplastic, excellent toughness and wear resistance. Absorbs moisture. For gears, bushings, rollers.",
        "cost_relative": "low",
    },
    "polymer_nylon_66": {
        "name": "Polymer Nylon 66",
        "family": "polymer",
        "common_names": ["Nylon 66", "polyamide 66"],
        "machinability_rating": 0.68,
        "hardness_typical": "75–90 HB",
        "density_g_cm3": 1.14,
        "tensile_strength_mpa": 80,
        "thermal_conductivity_w_mk": 0.24,
        "weldability": "not_recommended",
        "suitable_processes": ["cnc_milling", "cnc_turning", "injection_molding", "cutting_laser", "cutting_waterjet", "stamping"],
        "notes": "Thermoplastic polyamide, higher melting point than Nylon 6. For automotive, industrial components.",
        "cost_relative": "low",
    },
    "polymer_uhmwpe": {
        "name": "Polymer UHMWPE",
        "family": "polymer",
        "common_names": ["UHMWPE", "ultra-high molecular weight polyethylene"],
        "machinability_rating": 0.85,
        "hardness_typical": "50–60 HB",
        "density_g_cm3": 0.93,
        "tensile_strength_mpa": 42,
        "thermal_conductivity_w_mk": 0.42,
        "weldability": "not_recommended",
        "suitable_processes": ["cnc_milling", "cnc_turning", "cutting_laser", "cutting_waterjet"],
        "notes": "Highest wear-resistant plastic, low friction, impact-resistant. Lightest of engineering plastics. For bearings, sleds.",
        "cost_relative": "high",
    },
    "polymer_polycarbonate": {
        "name": "Polymer Polycarbonate",
        "family": "polymer",
        "common_names": ["polycarbonate", "PC"],
        "machinability_rating": 0.72,
        "hardness_typical": "80–95 HB",
        "density_g_cm3": 1.20,
        "tensile_strength_mpa": 63,
        "thermal_conductivity_w_mk": 0.21,
        "weldability": "not_recommended",
        "suitable_processes": ["cnc_milling", "cnc_turning", "cutting_laser", "cutting_waterjet", "injection_molding"],
        "notes": "Transparent, high impact strength, rigid. Sensitive to UV and scratching. For lenses, windows, covers.",
        "cost_relative": "medium",
    },
    "polymer_ptfe": {
        "name": "Polymer PTFE (Teflon)",
        "family": "polymer",
        "common_names": ["PTFE", "Teflon"],
        "machinability_rating": 0.55,
        "hardness_typical": "40–50 HB",
        "density_g_cm3": 2.16,
        "tensile_strength_mpa": 23,
        "thermal_conductivity_w_mk": 0.25,
        "weldability": "not_recommended",
        "suitable_processes": ["cnc_milling", "cnc_turning", "cutting_laser", "cutting_waterjet"],
        "notes": "Slippery, chemically inert, high temperature resistance to 260°C. Low strength. For seals, gaskets, non-stick coatings.",
        "cost_relative": "high",
    },
    "polymer_pps": {
        "name": "Polymer PPS",
        "family": "polymer",
        "common_names": ["PPS", "polyphenylene sulfide"],
        "machinability_rating": 0.62,
        "hardness_typical": "90–100 HB",
        "density_g_cm3": 1.64,
        "tensile_strength_mpa": 90,
        "thermal_conductivity_w_mk": 0.29,
        "weldability": "not_recommended",
        "suitable_processes": ["cnc_milling", "cnc_turning", "cutting_laser", "cutting_waterjet", "injection_molding"],
        "notes": "High-performance thermoplastic, excellent chemical resistance, thermal stability to 220°C. For automotive, oil/gas.",
        "cost_relative": "high",
    },
    "polymer_ultem": {
        "name": "Polymer ULTEM (PEI)",
        "family": "polymer",
        "common_names": ["ULTEM", "PEI", "polyetherimide"],
        "machinability_rating": 0.64,
        "hardness_typical": "95–110 HB",
        "density_g_cm3": 1.27,
        "tensile_strength_mpa": 95,
        "thermal_conductivity_w_mk": 0.28,
        "weldability": "not_recommended",
        "suitable_processes": ["cnc_milling", "cnc_turning", "cutting_laser", "cutting_waterjet", "injection_molding"],
        "notes": "Amorphous thermoplastic, excellent strength-to-weight, thermal stability to 170°C. For aerospace, medical.",
        "cost_relative": "high",
    },

    # COMPOSITES
    "composite_cfrp": {
        "name": "Composite Carbon Fiber Reinforced Polymer (CFRP)",
        "family": "composite",
        "common_names": ["CFRP", "carbon fiber", "carbon composite"],
        "machinability_rating": 0.35,
        "hardness_typical": "140–160 HB (Knoop)",
        "density_g_cm3": 1.55,
        "tensile_strength_mpa": 1275,
        "thermal_conductivity_w_mk": 4.1,
        "weldability": "not_recommended",
        "suitable_processes": ["cnc_milling", "cutting_laser", "cutting_waterjet", "cutting_plasma"],
        "notes": "Highest strength-to-weight ratio. Anisotropic. Difficult to machine (fiber pull-out). For aerospace, racing.",
        "cost_relative": "very_high",
    },
    "composite_gfrp": {
        "name": "Composite Fiberglass Reinforced Polymer (GFRP)",
        "family": "composite",
        "common_names": ["GFRP", "fiberglass", "glass fiber composite"],
        "machinability_rating": 0.45,
        "hardness_typical": "100–120 HB (Knoop)",
        "density_g_cm3": 1.85,
        "tensile_strength_mpa": 480,
        "thermal_conductivity_w_mk": 1.3,
        "weldability": "not_recommended",
        "suitable_processes": ["cnc_milling", "cutting_laser", "cutting_waterjet", "cutting_plasma"],
        "notes": "Good strength-to-weight, lower cost than carbon fiber. Produces fine dust when machined. For marine, automotive.",
        "cost_relative": "high",
    },
    "composite_kevlar_aramid": {
        "name": "Composite Kevlar/Aramid Reinforced Polymer",
        "family": "composite",
        "common_names": ["Kevlar", "aramid fiber", "aramid composite"],
        "machinability_rating": 0.30,
        "hardness_typical": "100–130 HB (Knoop)",
        "density_g_cm3": 1.47,
        "tensile_strength_mpa": 1020,
        "thermal_conductivity_w_mk": 2.8,
        "weldability": "not_recommended",
        "suitable_processes": ["cnc_milling", "cutting_laser", "cutting_waterjet"],
        "notes": "Excellent impact resistance, lower density than carbon fiber. Difficult to machine (fiber dulling). For armor, ropes.",
        "cost_relative": "very_high",
    },
    "composite_aluminum_mmc": {
        "name": "Composite Aluminum Metal Matrix Composite (MMC)",
        "family": "composite",
        "common_names": ["aluminum MMC", "Al-SiC", "metal matrix composite"],
        "machinability_rating": 0.32,
        "hardness_typical": "120–180 HB",
        "density_g_cm3": 2.85,
        "tensile_strength_mpa": 380,
        "thermal_conductivity_w_mk": 130,
        "weldability": "poor",
        "suitable_processes": ["cnc_milling", "cnc_turning", "cutting_laser", "edm_sinker"],
        "notes": "Aluminum matrix with ceramic reinforcement (SiC, Al2O3). High stiffness, low density. Difficult to machine.",
        "cost_relative": "very_high",
    },

    # CERAMICS
    "ceramic_alumina": {
        "name": "Ceramic Alumina (Al2O3)",
        "family": "ceramic",
        "common_names": ["alumina", "aluminum oxide", "corundum"],
        "machinability_rating": 0.10,
        "hardness_typical": "1900–2200 HV",
        "density_g_cm3": 3.97,
        "tensile_strength_mpa": 310,
        "thermal_conductivity_w_mk": 36.0,
        "weldability": "not_recommended",
        "suitable_processes": ["edm_sinker", "edm_wire", "cutting_laser"],
        "notes": "Hard, brittle ceramic. High melting point (2,072°C). For cutting tools, bearings, electrical insulation.",
        "cost_relative": "high",
    },
    "ceramic_silicon_carbide": {
        "name": "Ceramic Silicon Carbide (SiC)",
        "family": "ceramic",
        "common_names": ["SiC", "silicon carbide", "carborundum"],
        "machinability_rating": 0.08,
        "hardness_typical": "2200–2500 HV",
        "density_g_cm3": 3.21,
        "tensile_strength_mpa": 350,
        "thermal_conductivity_w_mk": 120,
        "weldability": "not_recommended",
        "suitable_processes": ["edm_sinker", "edm_wire", "cutting_laser"],
        "notes": "Extremely hard, high thermal conductivity. For abrasives, heat exchangers, semiconductor substrates.",
        "cost_relative": "high",
    },
    "ceramic_zirconia": {
        "name": "Ceramic Zirconia (ZrO2)",
        "family": "ceramic",
        "common_names": ["zirconia", "zirconium oxide"],
        "machinability_rating": 0.12,
        "hardness_typical": "1200–1300 HV",
        "density_g_cm3": 6.10,
        "tensile_strength_mpa": 900,
        "thermal_conductivity_w_mk": 2.8,
        "weldability": "not_recommended",
        "suitable_processes": ["edm_sinker", "edm_wire", "cutting_laser"],
        "notes": "High strength ceramic, good toughness. For cutting tools, wear parts, dental implants.",
        "cost_relative": "high",
    },
    "ceramic_silicon_nitride": {
        "name": "Ceramic Silicon Nitride (Si3N4)",
        "family": "ceramic",
        "common_names": ["silicon nitride", "Si3N4"],
        "machinability_rating": 0.10,
        "hardness_typical": "1600–1800 HV",
        "density_g_cm3": 3.24,
        "tensile_strength_mpa": 800,
        "thermal_conductivity_w_mk": 15.0,
        "weldability": "not_recommended",
        "suitable_processes": ["edm_sinker", "edm_wire", "cutting_laser"],
        "notes": "High-temperature ceramic, excellent thermal shock resistance. For turbine blades, cutting tools.",
        "cost_relative": "very_high",
    },
}


def get_material(name: str) -> Optional[dict]:
    """
    Case-insensitive lookup with fallback to common_names search.

    Args:
        name: Material name (e.g., "Ti-6Al-4V", "titanium grade 5", "6061")

    Returns:
        Material dict or None if not found.
    """
    # Normalize input
    normalized_input = name.lower().replace(" ", "_").replace("-", "_")

    # Direct key match
    if normalized_input in MATERIALS_CATALOG:
        return MATERIALS_CATALOG[normalized_input]

    # Search common_names
    for key, material in MATERIALS_CATALOG.items():
        for common in material.get("common_names", []):
            if common.lower() == name.lower():
                return material

    return None


def search_materials(query: str) -> list:
    """
    Search materials by query string in name, common_names, or family.

    Args:
        query: Search term (case-insensitive partial match)

    Returns:
        List of matching material dicts, sorted by match quality.
    """
    query_lower = query.lower()
    results = []

    for key, material in MATERIALS_CATALOG.items():
        match_score = 0

        # Check name (highest priority)
        if query_lower in material["name"].lower():
            match_score += 10

        # Check common_names
        for common in material.get("common_names", []):
            if query_lower in common.lower():
                match_score += 5

        # Check family
        if query_lower in material["family"].lower():
            match_score += 2

        if match_score > 0:
            results.append((match_score, material))

    # Sort by match score (descending)
    results.sort(key=lambda x: -x[0])
    return [mat for _, mat in results]


def materials_by_family(family: str) -> list:
    """
    Return all materials in a given family.

    Args:
        family: Family name (e.g., "carbon_steel", "aluminum_alloy", "composite")

    Returns:
        List of material dicts in that family.
    """
    family_lower = family.lower().replace("-", "_")
    return [
        material
        for material in MATERIALS_CATALOG.values()
        if material["family"].lower() == family_lower
    ]


# Process-Material Compatibility Matrix
# Maps each process family to compatible and incompatible material families.
PROCESS_MATERIAL_COMPATIBILITY = {
    "cnc_milling": {
        "compatible": [
            "carbon_steel",
            "stainless_steel",
            "tool_steel",
            "aluminum_alloy",
            "titanium_alloy",
            "nickel_alloy",
            "copper_alloy",
            "superalloy",
            "polymer",
        ],
        "incompatible": ["ceramic", "refractory"],
        "notes": "General-purpose subtractive manufacturing. Handles all ductile metals and plastics.",
    },
    "cnc_turning": {
        "compatible": [
            "carbon_steel",
            "stainless_steel",
            "tool_steel",
            "aluminum_alloy",
            "titanium_alloy",
            "nickel_alloy",
            "copper_alloy",
            "superalloy",
            "polymer",
        ],
        "incompatible": ["ceramic", "refractory", "composite"],
        "notes": "Rotational stock removal. Requires machinable materials with good chip formation.",
    },
    "welding_arc": {
        "compatible": [
            "carbon_steel",
            "stainless_steel",
            "nickel_alloy",
            "copper_alloy",
            "titanium_alloy",
            "aluminum_alloy",
        ],
        "incompatible": ["ceramic", "polymer", "composite", "refractory"],
        "notes": "Gas metal arc (GMAW), shielded metal arc (SMAW). Best on metals with low cracking sensitivity.",
    },
    "welding_laser": {
        "compatible": [
            "carbon_steel",
            "stainless_steel",
            "titanium_alloy",
            "aluminum_alloy",
            "nickel_alloy",
        ],
        "incompatible": ["ceramic", "polymer", "composite"],
        "notes": "High-energy density joining. Excellent precision, narrow HAZ. Limited penetration on thick stock.",
    },
    "welding_ebw": {
        "compatible": [
            "carbon_steel",
            "stainless_steel",
            "titanium_alloy",
            "nickel_alloy",
            "superalloy",
        ],
        "incompatible": ["ceramic", "polymer", "composite", "copper_alloy"],
        "notes": "Electron beam welding in vacuum. Premium process for high-strength critical joints.",
    },
    "bending_press_brake": {
        "compatible": [
            "carbon_steel",
            "stainless_steel",
            "aluminum_alloy",
            "copper_alloy",
            "titanium_alloy",
            "polymer",
        ],
        "incompatible": ["ceramic", "composite"],
        "notes": "Forming via punch and die. Requires formable material; high hardness increases spring-back.",
    },
    "cutting_laser": {
        "compatible": [
            "carbon_steel",
            "stainless_steel",
            "aluminum_alloy",
            "copper_alloy",
            "polymer",
            "composite",
            "ceramic",
        ],
        "incompatible": ["refractory"],
        "notes": "CO2/fiber laser cutting. Good for thin sheet, engraving. Thermal processes may affect edges.",
    },
    "cutting_plasma": {
        "compatible": [
            "carbon_steel",
            "stainless_steel",
            "aluminum_alloy",
            "copper_alloy",
            "composite",
        ],
        "incompatible": ["ceramic", "polymer", "refractory"],
        "notes": "High-temperature ionized gas cutting. Fast on thick plate, rough edge quality.",
    },
    "cutting_waterjet": {
        "compatible": [
            "carbon_steel",
            "stainless_steel",
            "aluminum_alloy",
            "copper_alloy",
            "titanium_alloy",
            "polymer",
            "composite",
            "ceramic",
        ],
        "incompatible": [],
        "notes": "Abrasive water jet. Universal process; no thermal distortion. Slower than laser/plasma.",
    },
    "stamping": {
        "compatible": [
            "carbon_steel",
            "stainless_steel",
            "aluminum_alloy",
            "copper_alloy",
            "polymer",
        ],
        "incompatible": ["ceramic", "composite", "refractory"],
        "notes": "High-volume forming via press and die. Requires material with adequate formability.",
    },
    "edm_wire": {
        "compatible": [
            "carbon_steel",
            "stainless_steel",
            "tool_steel",
            "titanium_alloy",
            "nickel_alloy",
            "superalloy",
            "ceramic",
            "refractory",
        ],
        "incompatible": ["polymer", "composite"],
        "notes": "Wire EDM: electrical discharge via thin wire. Ideal for hard materials, complex geometries.",
    },
    "edm_sinker": {
        "compatible": [
            "carbon_steel",
            "stainless_steel",
            "tool_steel",
            "titanium_alloy",
            "nickel_alloy",
            "superalloy",
            "ceramic",
            "refractory",
        ],
        "incompatible": ["polymer", "composite"],
        "notes": "Sink/cavity EDM. Converts hardened steel dies, carbide parts without mechanical stress.",
    },
    "injection_molding": {
        "compatible": ["polymer"],
        "incompatible": [
            "carbon_steel",
            "stainless_steel",
            "ceramic",
            "composite",
            "refractory",
        ],
        "notes": "Thermoplastic/thermoset molding. High volume, complex geometry, poor tolerance control.",
    },
    "inspection_cmm": {
        "compatible": [
            "carbon_steel",
            "stainless_steel",
            "aluminum_alloy",
            "titanium_alloy",
            "copper_alloy",
            "ceramic",
        ],
        "incompatible": ["polymer"],
        "notes": "Coordinate measurement machine. Surfaces must be sufficiently rigid and reflective.",
    },
    "inspection_vision": {
        "compatible": [
            "carbon_steel",
            "stainless_steel",
            "aluminum_alloy",
            "titanium_alloy",
            "copper_alloy",
            "ceramic",
            "polymer",
        ],
        "incompatible": [],
        "notes": "Optical/RGB surface inspection. Works on any reflective or opaque surface.",
    },
}
